### ISSUE TITLE
Invalid StreamInterface::read implementation

### ISSUE THREAD

**Issue by ajgarlag** [php-http/socket-client#13]
When I call Http\Client\Socket\Stream::read($length) method with a `$length` value greater than the stream size, an StreamException is [thrown](https://github.com/php-http/socket-client/blob/0d986fba4142d8ee2c2987bfaaaff282544af7af/src/Stream.php#L167) with the message "Cannot read more than %s"(also a sprintf call is missed here).

But the StreamInterface::read documentation [describes](https://github.com/php-fig/http-message/blob/f22d9b6dd24ec003c7996813d505e4a9b1b6390d/src/StreamInterface.php#L127) that it can returns fewer than `$length` bytes, so the Http\Client\Socket\Stream::read must return the remaining stream content up to `$length` bytes instead of throwing an exception.

**Comment by joelwurtz** [comment]
Thanks, closed in #14
