### ISSUE TITLE
Socket adapter Init

### ISSUE THREAD

**Issue by joelwurtz** [php-http/socket-client#2]
Apart from some dependencies issues, the socket client is nearly done (we can always add thing, but it is ok for a first version IMO)

It's available here: https://github.com/joelwurtz/socket-adapter-temp

How do you want to proceed for review ? merging it here ?

**Comment by sagikazarmark** [comment]
I added you as a collaborator to this project. Feel free to push, but before doing so, please make sure of the following:

- Check that a proper LICENSE is included. I prefer having The PHP HTTP team as a licensor, but you are free to leave yourself if you prefer.
- Make sure to include full credit: it is your work, the group just hosts it (actually Github does technically, the group just gives its name to it).
- Please try to follow the latest conventions (travis, git, scrutinizer, editor configs) (I recently added the Contributor Code of Conduct, you can see it in the boilerplate repo.), but as always, you are free to have your own concepts. However I think it is generally better to remain consistent in the organization.

I would be happy if we could have you on board as the maintainer of this project. Thanks for all your work.

**Comment by joelwurtz** [comment]
> I added you as a collaborator to this project. Feel free to push, but before doing so, please make sure of the following...

I use the boilerplate package earlier to match the current package (and add the CONDUCT.md also)

> I would be happy if we could have you on board as the maintainer of this project. Thanks for all your work.

I will try to do my best to answer issue and pull requests, but as i do this mainly in my free time, i can just not be in the mood sometimes...

Anyway don't hesite to blame my poor english skills on the documentation, and missing / bug things in this library

**Comment by sagikazarmark** [comment]
> but as i do this mainly in my free time

Sure thing, everyone of us does. That's why the organization is good: if one of us gets hit by a bus, someone else can take over the project.

**Comment by joelwurtz** [comment]
http://mtov.github.io/Truck-Factor/ :)

And when you have time can you add integrations / hook (scrutinizer / travis / packagist ...) for this repository.

Thanks for the trust !

**Comment by sagikazarmark** [comment]
LOL :D

Integratons are set up.

**Comment by joelwurtz** [comment]
Thanks :beers:
