### ISSUE TITLE
Stream::__toString() must not thrown an exception

### ISSUE THREAD

**Issue by Nyholm** [php-http/socket-client#25]
From @shaneiseminger

> Method Http\Client\Socket\Stream::__toString() must not throw an exception
> 
> When using this library with happyr/linkedin-api-client, I'm getting the above fatal error. Just needs a try/catch block in __toString(). Happy to submit a pull request.

(Originally posted here: https://github.com/php-http/documentation/issues/135)

**Comment by shaneiseminger** [comment]
Thanks!
