### ISSUE TITLE
HTTP2 Support

### ISSUE THREAD

**Issue by joelwurtz** [php-http/socket-client#36]
I believe there is now enough support in php and libraries to do that "easily"

 * Negotiate protocols with alpn_protocols option of tls context (added in php 7.0)
 * Headers compression by using https://github.com/amphp/hpack

Biggest problem is on the API, as a request can receive multiple reponses, it will certainly need a decorator around a PSR7 Response (A specific stream implementation) / decorator)

**Comment by DarkGhostHunter** [comment]
Is this maintained? Plans to integrate this?

**Comment by joelwurtz** [comment]
No time to do it on my side, so don't think so :)
