### ISSUE TITLE
Incorrect 2nd parameter for exceptions

### ISSUE THREAD

**Issue by beloglazov91** [php-http/socket-client#39]
`Wrong parameters for Http\Client\Socket\Exception\TimeoutException([string $message [, long $code [, Throwable $previous = NULL]]])" {"exception":"[object] (Error(code: 0): Wrong parameters for Http\\Client\\Socket\\Exception\\TimeoutException([string $message [, long $code [, Throwable $previous = NULL]]]) at php-http/socket-client/src/ResponseReader.php:51`

I found a problem in the 2nd parameter for thrown exception. There passing RequestInterface object and not exception code.

**Comment by beloglazov91** [comment]
Sorry, looks like it already was fixed.

**Comment by xgin** [comment]
It was fixed, but not released yet.
@joelwurtz @Nyholm could you push a tag with a new version to make the package available on Packagist?

**Comment by Nyholm** [comment]
I've just released 1.4.1. Thank you.
