### ISSUE TITLE
Move documentation to documentation

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/socket-client#4]
Eventually (when the current docs is updated with httplug content) documentation should go right into the official docs.

**Comment by sagikazarmark** [comment]
Is this already done? If so, can we remove docs from the repo?

**Comment by joelwurtz** [comment]
Not done

**Comment by sagikazarmark** [comment]
It seems to me that a PR is merged.

**Comment by joelwurtz** [comment]
Yep keep that open, i want to add a link to the documentation in the readme and remove stuff to avoid duplication

**Comment by sagikazarmark** [comment]
What's the status of this?

**Comment by joelwurtz** [comment]
done in 8207227256abe38c05fa64247e1ad0b93d2d1ab8
