### ISSUE TITLE
Tag version 2.0.0

### ISSUE THREAD

**Issue by cweiske** [php-http/socket-client#47]
**Description**
PSR-18 support has been added two years ago in #38, but there is no tag for version 2.0.0 (stable) - only for 2.0.0-beta1

It would be nice if the package got an official stable 2.0.0 release with PSR-18 support.

**Comment by driehle** [comment]
Yes, really looking forward to this as well!

**Comment by emodric** [comment]
I'd like to see this as well! Thanks!

**Comment by wizhippo** [comment]
Me too.

**Comment by driehle** [comment]
@joelwurtz @Nyholm any news on this? Your reply would be greatly appreciated here! :)

**Comment by andrew-demb** [comment]
Hello!
Are there some issues, that block package from release?

May we help?

**Comment by joelwurtz** [comment]
There were some fixes to do to make it rights, it's done and tagged
