### ISSUE TITLE
Add PHP 8 support

### ISSUE THREAD

**Issue by flavioheleno** [php-http/socket-client#57]
**Description**
PHP 8.0.0 has been launched for a [month](https://www.php.net/archive/2020.php#2020-11-26-3) already, PHP 8.0.1-RC1 is already [tagged](https://externals.io/message/112535) and the library still does not support it.

**Example**
It is not really a feature by itself, but it's about supporting the latest language version.

**Additional context**
I'm working on a PR for this :)

**Comment by joelwurtz** [comment]
There was already a PR for that, i just merge it and release 2.1.0 with support for PHP8
